### ISSUE TITLE
Polish version

### ISSUE THREAD

**Issue by zcaalock** [antontimmermans/MOMCDM#4] opened 2019-04-05 13:21 UTC
done the translation :)

[Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3048058/Localization.Polish.txt)

didn`t have much time to test it ingame. If i find any typos ill post it here. 

best

**Comment by antontimmermans** [comment] 2019-04-06 11:38
@zcaalock Thx, i am integrating the result.
i missed the translation for one event text and I added a 'secret'button to enable test mode.

i used Google translate for that to make is look polish, but can you check this please?
`EventRitualCompSearchPass.text,Szuflada pozostaje zamknięta bez względu na to, ile pociągniesz. W desperackiej próbie otwarcia odrywasz przedni panel szuflady. Sięgasz do środka i znajdujesz czerwone świece i bibeloty z symbolami okultystycznymi. Otrzymasz unikalny element {c: QItemRitualComponents}. Usuń token wyszukiwania.
PuzzleFuseBoxSmall.button1,{qst:OPEN}
UIIntroductionTextTop.button1,{qst:CONTINUE}
UITestEnable.button1,TAK
UITestEnable.uitext,\n
UITestEnable.text,Wybrałeś przycisk włączania testu.\n\nWybierz <b>Anuluj</b>, jeśli chcesz kontynuować odtwarzanie scenariusza w zamierzony sposób.\n\n<b>OSTRZEŻENIE</b>: ENABLE TESTMODE pomija wprowadzenie, umieszcza przycisk testowy i umożliwia ogłaszanie rundy.
`

Original text:
`EventRitualCompSearchPass.text,The drawer remains stuck no matter how much you pull. In a desperate attempt to open it, you break away the front panel of the drawer. You reach inside and find some red candles and trinkets with occult symbols. You receive the {c:QItemRitualComponents} Unique item. Remove the Search Token.
PuzzleFuseBoxSmall.button1,{qst:OPEN}
UIIntroductionTextTop.button1,{qst:CONTINUE}
UITestEnable.button1,YES
UITestEnable.uitext,\n
UITestEnable.text,You have selected the test enable button.\n\nSelect <b>Cancel</b> if you wish to continue play the scenario as it was intended.\n\n<b>WARNING</b>: ENABLE TESTMODE skips introduction, places a test button and enables round announcement.`

**Comment by zcaalock** [comment] 2019-04-06 15:01
EventRitualCompSearchPass.text,Szuflada pozostaje zamknięta bez względu na to, jak mocno szarpiesz. W desperackiej próbie otwarcia odrywasz przedni panel szuflady. Sięgasz do środka i znajdujesz czerwone świece i bibeloty z symbolami okultystycznymi. Otrzymujesz przedmiot unikalny {c:QItemRitualComponents}. Usuń żeton przeszukania. PuzzleFuseBoxSmall.button1,{qst:OPEN} UIIntroductionTextTop.button1,{qst:CONTINUE} UITestEnable.button1,TAK UITestEnable.uitext,\n UITestEnable.text,Wybrałeś przycisk włączania testu.\n\nWybierz <b>Anuluj</b>, jeśli chcesz kontynuować odtwarzanie scenariusza w zamierzony sposób.\n\n<b>OSTRZEŻENIE</b>: ENABLE TESTMODE pomija wprowadzenie, umieszcza przycisk testowy i umożliwia ogłaszanie rundy.

**Comment by antontimmermans** [comment] 2019-04-08 19:58
@zcaalock, I made CDM also playable with base set only and i need one more translation for a tileplacement. Can you please do one more:
You still recognize some religious paintings and statues in this room, but time has not been kind to them. It also looks as if this old chapel's last function was that of a diningroom. Place the {c:TileAChapelBase} tile as indicated and remove the Explore Token connecting to it.
A huge mess in the kitchen area makes it inaccessible. Threat this part of the tile as inaccessible.

**Comment by zcaalock** [comment] 2019-04-09 07:47
Chociaż czas nie był dla nich łaskawy rozpoznajesz niektóre religijne obrazy i posągi w tym pokoju. Wygląda na to, że ostatnią funkcją tej starej kaplicy była jadalnia. Umieść płytkę {c:TileAChapelBase} jak wskazano i usuń łączący się z nią żeton Eksploracji.
Ogromny bałagan w kuchni sprawia, że ta część kuchni jest niedostępna. Nie da się tu wejść.

**Comment by chrismaliszewski** [comment] 2019-04-09 21:09
I'm checking Polish translation. A question regarding the English translation. @antontimmermans, could you please confirm if you wanted to name the room "Speakeasy" or it's rather a bar of the kind https://www.urbandictionary.com/define.php?term=Speakeasy?

**Comment by zcaalock** [comment] 2019-04-10 09:17
there is no equivalent word for speakeasy in polish . It could be "illegal bar" but it won`t be secret anymore

**Comment by chrismaliszewski** [comment] 2019-04-10 09:30
I know. But the word Speakeasy doesn't have any connotations nor ring a bell in Polish either. So I was thinking about changing the name to something more Polish but the author's meaning of the word is important. 

I've just asked 'older people' and during PRL in Kraków there was a(n) (in)famous bar where people opposing government were meeting. It is called (yes, it's still open) Pod Baranami. It matches the idea of Speakeasies and could be a good name for the bar and some people may understand the meaning behind.

**Comment by antontimmermans** [comment] 2019-04-11 15:07
Speakeasy was in times of the Prohibition (in USA) the place where illegally produced alcohol was served. It may be difficult to translate that meaning to Polish since I don't recall Poland ever suffered a prohibition.

Maybe we should keep it simple: In the English version of MOM the tile is called "speakeasy". What is the tile of that tile in the Polish version of the game? Players will recognize which tile to expect and part of the fun in the story is the anticipation of what may happen...

**Comment by chrismaliszewski** [comment] 2019-04-11 17:01
I don't have Polish version of the game :). @zcaalock, do you have one?

**Comment by zcaalock** [comment] 2019-04-11 18:02
its called "nielegalny bar" illegal bar :D

btw i didnt have time before to run polish version and i see some typos now. Editor really need function to cycle through events because manually finding and opening each one is relay painful. The best way to find errors is when you go through every event in editor and see how the text looks.

@chrismaliszewski did you start checking Polish version?

**Comment by chrismaliszewski** [comment] 2019-04-11 19:38
Ok, so I change "speakeasy" to "nielegalny bar". 

Yes, I started checking your translation. It's good. I made some changes here and there but nothing major. Here is the file that I checked until line 261:
[Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3070283/Localization.Polish.txt)
I'll continue checking the file as I did and, if you want, you could start checks from the end of the file and we can meet in the middle if you'd like and finally we can merge the file. 

I'll be in touch.

**Comment by chrismaliszewski** [comment] 2019-04-11 20:12
@antontimmermans, a question regarding lines 401 & 402. It's the first time that I see "staring to sth" form. Should there be "at" instead of "to"? Just to be clear, I'm not checking English. I only read it from time to time if I find Polish translation odd.

**Comment by antontimmermans** [comment] 2019-04-11 20:24
i guess you are right: "staring at you is better" thx :)

**Comment by chrismaliszewski** [comment] 2019-04-11 20:46
@zcaalock, a question regarding 514. "The" in English points to a particular thing(s). Here to **the particular events**/time when everyone died. So current Polish translation ("Czy ta książka jest powiązana z wydarzeniami?") is not accurate as it doesn't exactly say "what/which events" but I'm not sure how to translate it to transfer the meaning. 

Do you prefer: 
1. "Czy ta książka jest powiązana z tymi wydarzeniami?" (the exact translation) or
2. "Czy ta książka ma związek z tym wszystkim?" (Is that book related to all of the things here?) or
3. you have other suggestions?

As for now, I'll translate it to 1.

**Comment by chrismaliszewski** [comment] 2019-04-11 20:59
@zcaalock, up to line 623
[Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3070575/Localization.Polish.txt)

**Comment by chrismaliszewski** [comment] 2019-04-12 13:38
@antontimmermans, while checking weird/funny/odd/etc Polish translations I started to check English translations too. I created a bunch of minor changes that I'd make to the English version:
631: there are two "as if"s one after another as well as the sentences don't sound right. The first one tells about Pastor but another out of nowhere about keys which have nothing in common with the previous sentence and as a result, the story doesn't flow, at least for me. 
My suggestion: "Howard Bechman's ghost looks at you with hollow eyes. The set of keys he once attached to his belt fall to the ground but before they touch the floor, they reappear at his belt. This image repeats as if the falling keys are caught in a time loop.".
665: I think it sounds better than using the word "hand" twice in the same sentence. 
My suggestion: "The ghostly keys fall straight through your hand leaving you empty-handed.".
666: I think the below proposition flows a little bit better.
My suggestion: "You attempt to catch the keys. You had a distinct feeling you would catch them but instead, you have just missed as they, again, reappear at Howard Bechman's belt."
785: I'd bold the last part of the sentence as in 787 so it stands out more.
800 & 801: a strange usage of "set up sth **in**". I think the "in" is not needed. The "in" would be ok if there was after it as "set up sth in somewhere". 
813 & 814: Merge two sentences together into one.
My suggestion: "{qst:GHOSTCANDLEPART1} is a room that you don't recognize and one you have not explored yet."
840: I think the "(but not all)" part is not needed as the word "some" suggests so. 
889: In the second sentence, I'm lacking the direct indication that the person responsible lived in this mansion and now is dead/is one of the ghosts/is not a person who must have been in this mansion but created the disaster, run away and lived happily and ever after. 
1025: different time/wrong usage. I prefer the first below option.
My suggestions: You see an image of Howard looking in a drawer. He frowns at what he discovers, shrugs and then closes the drawer. **OR** You see an image of Howard looking in a drawer, frowning at what he discovers, shrugging and then closing the drawer.
1089: unclear lyrical; book or symbol?
My suggestion: The covers of these books are decorated with incomprehensible symbols but you cannot remember which one was drawn on the Pastor's book.
1614: word haunted used twice :) - "You explain to them that the mansion is no longer haunted, scary, but not haunted." I'm not sure what you wanted to say here, so no suggestions from my side.

**Comment by chrismaliszewski** [comment] 2019-04-13 19:48
@zcaalock, can you check Polish translation of Ritual Components?

**Comment by chrismaliszewski** [comment] 2019-04-13 20:06
@zcaalock , @antontimmermans, Polish translation fully checked: [Localization.Polish.txt](https://github.com/antontimmermans/MOMCDM/files/3076689/Localization.Polish.txt)

**Comment by zcaalock** [comment] 2019-04-15 11:07
"Ritual Components" Elementy rytuału

**Comment by antontimmermans** [comment] 2019-04-15 18:48
> @antontimmermans, while checking weird/funny/odd/etc Polish translations I started to check English translations too. I created a bunch of minor changes that I'd make to the English version:
> 631: there are two "as if"s one after another as well as the sentences don't sound right. The first one tells about Pastor but another out of nowhere about keys which have nothing in common with the previous sentence and as a result, the story doesn't flow, at least for me.
> My suggestion: "Howard Bechman's ghost looks at you with hollow eyes. The set of keys he once attached to his belt fall to the ground but before they touch the floor, they reappear at his belt. This image repeats as if the falling keys are caught in a time loop.".
> 665: I think it sounds better than using the word "hand" twice in the same sentence.
> My suggestion: "The ghostly keys fall straight through your hand leaving you empty-handed.".
> 666: I think the below proposition flows a little bit better.
> My suggestion: "You attempt to catch the keys. You had a distinct feeling you would catch them but instead, you have just missed as they, again, reappear at Howard Bechman's belt."
> 785: I'd bold the last part of the sentence as in 787 so it stands out more.
> 800 & 801: a strange usage of "set up sth **in**". I think the "in" is not needed. The "in" would be ok if there was after it as "set up sth in somewhere".
> 813 & 814: Merge two sentences together into one.
> My suggestion: "{qst:GHOSTCANDLEPART1} is a room that you don't recognize and one you have not explored yet."
> 840: I think the "(but not all)" part is not needed as the word "some" suggests so.
> 889: In the second sentence, I'm lacking the direct indication that the person responsible lived in this mansion and now is dead/is one of the ghosts/is not a person who must have been in this mansion but created the disaster, run away and lived happily and ever after.
> 1025: different time/wrong usage. I prefer the first below option.
> My suggestions: You see an image of Howard looking in a drawer. He frowns at what he discovers, shrugs and then closes the drawer. **OR** You see an image of Howard looking in a drawer, frowning at what he discovers, shrugging and then closing the drawer.
> 1089: unclear lyrical; book or symbol?
> My suggestion: The covers of these books are decorated with incomprehensible symbols but you cannot remember which one was drawn on the Pastor's book.
> 1614: word haunted used twice :) - "You explain to them that the mansion is no longer haunted, scary, but not haunted." I'm not sure what you wanted to say here, so no suggestions from my side

@chrismaliszewski thank you for your suggestions for the english text improvement. I have implemented them all in the next update.

**Comment by antontimmermans** [comment] 2019-04-15 18:59
> "Ritual Components" Elementy rytuału

@zcaalock @chrismaliszewski 
In the attached polish text file I found: **rytualne elementy**
Based on this last comment you made, should I replace this with: **elementy rytualne** ?

FYI: google translate suggests:  **składniki rytualne** for ritual components but i'll take your translation instead. i assume that this is the same text as used on the polish version of the card "ritual components"

**Comment by chrismaliszewski** [comment] 2019-04-15 20:04
@antontimmermans, you're good with Polish :). Yes, line 1384 should be: "Ten krąg musi być zasilany przez Elementy Rytualne. Może znajdziesz coś w tym domu."

I'd take @zcaalock's translation as I also think the translation given was taken from the MoM's Polish Ritual Components card.

**Comment by zcaalock** [comment] 2019-04-15 21:01
@chrismaliszewski @antontimmermans btw i`ve started to translate another scenario :D https://github.com/antontimmermans/MOMDATD/issues/18

**Comment by antontimmermans** [comment] 2019-04-19 12:28
I am closing this issue as it it released in V1.3. Please make a **new** ticket if there should be any correction or update.

**Closed as completed by antontimmermans** 2019-04-19 12:28 UTC
